In [5]:
x=...
def main(*args):
    for i,arg in enumerate(args):
        print(f'Argument {i+1}:{arg}')
    if not args:
        print(f"\nUnspecified arguments: {x}")
main(1,2,3,'Pawan Yadav')
main(22,[1,2,3,4],'Pawan','Yadav')
main()

Argument 1:1
Argument 2:2
Argument 3:3
Argument 4:Pawan Yadav
Argument 1:22
Argument 2:[1, 2, 3, 4]
Argument 3:Pawan
Argument 4:Yadav

Unspecified arguments: Ellipsis


In [6]:
def call_function(x,*args,**kwargs):
    return x(*args,**kwargs)
def add(x,y):
    return x+y
r=call_function(add,10,22)
print(r)
def message(name,text='Good Evening!'):
    return f'{name},{text}!'
r=call_function(message,'Pawan',text=...)
print(r)

32
Pawan,Ellipsis!


In [7]:
import numpy as np
def slice_3D(arr):
    return arr[...,:2]
nums = np.array([[[1, 2, 3], [4, 5, 6]],
                           [[7, 8, 9], [10, 11, 12]],
                           [[13, 14, 15], [16, 17, 18]]])
print('Original Multidimensional array:')
print(nums)
slice=slice_3D(nums)
print("\nSlices the first two elements from the said array:")
print(slice)

Original Multidimensional array:
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]

Slices the first two elements from the said array:
[[[ 1  2]
  [ 4  5]]

 [[ 7  8]
  [10 11]]

 [[13 14]
  [16 17]]]


In [8]:
print("\nContaining numbers from 10 to 20, but leaves a gap at odd positions:")
x=[i if i%2!=0 else ... for i in range(1,11)]
print(x)
print("\nContaining numbers from 10 to 20, but leaves a gap at odd positions:")
x=[i if i%2==0 else ... for i in range(10,21)]
print(x)


Containing numbers from 10 to 20, but leaves a gap at odd positions:
[1, Ellipsis, 3, Ellipsis, 5, Ellipsis, 7, Ellipsis, 9, Ellipsis]

Containing numbers from 10 to 20, but leaves a gap at odd positions:
[10, Ellipsis, 12, Ellipsis, 14, Ellipsis, 16, Ellipsis, 18, Ellipsis, 20]


In [9]:
x=[1,2,3,5,7,8,...,'pawan','yadav']
y=...
if y in x:
    print('Ellipsis is Present in Given List!')
else:
    print('Ellipsis not Present in Given List!')
print('.............................................')
x=[1,2,3,5,7,8,'pawan','yadav']
y=...
if y in x:
    print('Ellipsis is Present in Given List!')
else:
    print('Ellipsis not Present in Given List!')
print('.............................................')
x=[1,2,3,5,7,8,...,'pawan','yadav']
y=...
for i in x:
    if i is y:
        print('Skipping...')
        continue
    print(f'Reading item:{i}')
print('.............................................')

Ellipsis is Present in Given List!
.............................................
Ellipsis not Present in Given List!
.............................................
Reading item:1
Reading item:2
Reading item:3
Reading item:5
Reading item:7
Reading item:8
Skipping...
Reading item:pawan
Reading item:yadav
.............................................


In [10]:
#Used online compiler for run this code
import numpy as np
try:
    x=np.array([[[1,2],[3,4]], [..., ...] , [[5,6],[7,8]]])
    print(x)
except Exception as e:
    print(e)

setting an array element with a sequence. The requested array has an inhomogeneous shape after 2 dimensions. The detected shape was (3, 2) + inhomogeneous part.


In [11]:
def main(s,e,st,sk):
    for i in range(s,e,st):
        if sk>0:
            yield i
            sk-=1
        else:
            yield '...'
            sk=sk+st-1
gen=main(1,30,2,4)
for i in gen:
    print(i,end=', ')

1, 3, 5, 7, ..., 11, ..., 15, ..., 19, ..., 23, ..., 27, ..., 

In [12]:
x=[1,2,3]
y=[4,5,6]
z=[7,8,9]
a=x+[...]+y+[...]+z
print(a)

[1, 2, 3, Ellipsis, 4, 5, 6, Ellipsis, 7, 8, 9]


In [13]:
class ellipsis:
    def __init__(self,ellipsis1,ellipsis2,ellipsis3,ellipsis4=...):
        self.ellipsis1=ellipsis1
        self.ellipsis2=ellipsis2
        self.ellipsis3=ellipsis3
        self.ellipsis4=ellipsis4
    def set_attributes(self,value):
        self.ellipsis4=value
obj=ellipsis('Pawan','Yadav','Yaduvanshi')
print("Attribute 1:", obj.ellipsis1)
print("Attribute 2:", obj.ellipsis2)
print("Attribute 3:", obj.ellipsis3)
print("Attribute 4:", obj.ellipsis4) 
obj.set_attributes('AI Developer!')
print('Modified Attribute:',obj.ellipsis4)

Attribute 1: Pawan
Attribute 2: Yadav
Attribute 3: Yaduvanshi
Attribute 4: Ellipsis
Modified Attribute: AI Developer!
